Whanganui_MapScripts::
	.byte 0
Whanganui_EventScript_RiverMan::
	msgbox Whanganui_Text_RiverMan, MSGBOX_NPC
	end
Whanganui_EventScript_Kid::
	msgbox Whanganui_Text_Kid, MSGBOX_NPC
	end
Whanganui_EventScript_RiverSign::
	msgbox Whanganui_Text_RiverSign, MSGBOX_SIGN
	end
Whanganui_Text_RiverMan:
	.string "The awa is our tupuna. Our\n"
	.string "ancestor. Ko au te awa, ko te\l"
	.string "awa ko au.\p"
	.string "I am the river and the river\n"
	.string "is me.\p"
	.string "You look like someone who could\n"
	.string "use a river to belong to.$"
Whanganui_Text_Kid:
	.string "I'm going to paddle the whole\n"
	.string "awa one day! Source to sea!\p"
	.string "…After lunch, though.$"
Whanganui_Text_RiverSign:
	.string "WHANGANUI\p"
	.string "“Ko au te awa, ko te awa ko au.”$"
