AhuririSeasideHouse3_MapScripts::
	.byte 0

AhuririSeasideHouse3_EventScript_Nurse2::
	lock
	faceplayer
	msgbox AhuririSeasideHouse3_Text_Nurse2, MSGBOX_DEFAULT
	release
	end

AhuririSeasideHouse3_Text_Nurse2:
	.string "I nursed through the quake\n"
	.string "centennial. You know what got\l"
	.string "us through? Neighbours.\p"
	.string "Whatever's rotten in this\n"
	.string "town, the people aren't.\l"
	.string "Remember that when you leave.$"

