Ngamotu_MapScripts::
	.byte 0

Ngamotu_EventScript_MountainMan::
	msgbox Ngamotu_Text_MountainMan, MSGBOX_NPC
	end
Ngamotu_EventScript_StreetWoman::
	msgbox Ngamotu_Text_StreetWoman, MSGBOX_NPC
	end
Ngamotu_EventScript_GymKid::
	msgbox Ngamotu_Text_GymKid, MSGBOX_NPC
	end
Ngamotu_EventScript_SurfKid::
	msgbox Ngamotu_Text_SurfKid, MSGBOX_NPC
	end
Ngamotu_EventScript_TaranakiSign::
	msgbox Ngamotu_Text_TaranakiSign, MSGBOX_SIGN
	end

Ngamotu_Text_MountainMan:
	.string "Taranaki stands alone because\n"
	.string "of a fight over a woman, they\l"
	.string "say.\p"
	.string "He walked west and never looked\n"
	.string "back. Perfect cone. No regrets\l"
	.string "you can see from here.$"
Ngamotu_Text_StreetWoman:
	.string "Cleanest, windiest, arty little\n"
	.string "city in the country.\p"
	.string "We measure the wind in 'hold\n"
	.string "onto your kid' units.$"
Ngamotu_Text_GymKid:
	.string "Our gym's shut till the region\n"
	.string "sorts itself out.\p"
	.string "Everything's shut till the\n"
	.string "region sorts itself out!$"
Ngamotu_Text_SurfKid:
	.string "Black sand beaches! The sand's\n"
	.string "hot enough to fry an egg.\p"
	.string "…We tried. Nan was not pleased.$"
Ngamotu_Text_TaranakiSign:
	.string "MOUNT TARANAKI LOOKOUT\p"
	.string "“He stands alone by choice.\n"
	.string "Please don't climb him uninvited.”$"
