// Generated by tools_pounamu/townmap/apply.py from layout.py - edit there, not here.
// Where each Pounamu outdoor map sits on the town map: its cells in the order the map
// runs (top to bottom, or left to right), so the player's head moves along a long road.
#define POUNAMU_MAP_CELLS_MAX 8

struct PounamuMapCells
{
    u16 map;   // (group << 8) | num
    u8 alongX;
    u8 count;
    u8 x[POUNAMU_MAP_CELLS_MAX];
    u8 y[POUNAMU_MAP_CELLS_MAX];
};

static const struct PounamuMapCells sPounamuMapCells[] =
{
    {(MAP_GROUP(MAP_TAMAKI_MAKAURAU) << 8) | MAP_NUM(MAP_TAMAKI_MAKAURAU), 0, 1, {24}, {6}},
    {(MAP_GROUP(MAP_TAURANGA) << 8) | MAP_NUM(MAP_TAURANGA), 0, 1, {25}, {9}},
    {(MAP_GROUP(MAP_OPOTIKI) << 8) | MAP_NUM(MAP_OPOTIKI), 0, 1, {25}, {11}},
    {(MAP_GROUP(MAP_TURANGA) << 8) | MAP_NUM(MAP_TURANGA), 0, 1, {25}, {12}},
    {(MAP_GROUP(MAP_AHURIRI_CITY) << 8) | MAP_NUM(MAP_AHURIRI_CITY), 0, 1, {23}, {12}},
    {(MAP_GROUP(MAP_HERETAUNGA_TOWN) << 8) | MAP_NUM(MAP_HERETAUNGA_TOWN), 0, 1, {22}, {12}},
    {(MAP_GROUP(MAP_ROTORUA) << 8) | MAP_NUM(MAP_ROTORUA), 0, 1, {24}, {10}},
    {(MAP_GROUP(MAP_TAUPO) << 8) | MAP_NUM(MAP_TAUPO), 0, 1, {23}, {10}},
    {(MAP_GROUP(MAP_NGAMOTU) << 8) | MAP_NUM(MAP_NGAMOTU), 0, 1, {20}, {8}},
    {(MAP_GROUP(MAP_WHANGANUI) << 8) | MAP_NUM(MAP_WHANGANUI), 0, 1, {20}, {11}},
    {(MAP_GROUP(MAP_WELLINGTON) << 8) | MAP_NUM(MAP_WELLINGTON), 0, 1, {17}, {12}},
    {(MAP_GROUP(MAP_WAITOHI) << 8) | MAP_NUM(MAP_WAITOHI), 0, 1, {16}, {11}},
    {(MAP_GROUP(MAP_WHAKATU) << 8) | MAP_NUM(MAP_WHAKATU), 0, 1, {16}, {10}},
    {(MAP_GROUP(MAP_OTAUTAHI) << 8) | MAP_NUM(MAP_OTAUTAHI), 0, 1, {11}, {13}},
    {(MAP_GROUP(MAP_OTEPOTI) << 8) | MAP_NUM(MAP_OTEPOTI), 0, 1, {5}, {14}},
    {(MAP_GROUP(MAP_ORCHARD_ROAD) << 8) | MAP_NUM(MAP_ORCHARD_ROAD), 0, 2, {23, 22}, {12, 12}},
    {(MAP_GROUP(MAP_ROUTE2_BAY) << 8) | MAP_NUM(MAP_ROUTE2_BAY), 0, 1, {23}, {12}},
    {(MAP_GROUP(MAP_ROUTE2_NORTH) << 8) | MAP_NUM(MAP_ROUTE2_NORTH), 0, 1, {24}, {12}},
    {(MAP_GROUP(MAP_ROUTE2_EAST) << 8) | MAP_NUM(MAP_ROUTE2_EAST), 0, 3, {25, 24, 24}, {13, 13, 12}},
    {(MAP_GROUP(MAP_ROUTE35_A) << 8) | MAP_NUM(MAP_ROUTE35_A), 0, 2, {27, 26}, {12, 12}},
    {(MAP_GROUP(MAP_ROUTE35_B) << 8) | MAP_NUM(MAP_ROUTE35_B), 0, 2, {26, 27}, {11, 11}},
    {(MAP_GROUP(MAP_ROUTE2_BOP) << 8) | MAP_NUM(MAP_ROUTE2_BOP), 0, 1, {25}, {10}},
    {(MAP_GROUP(MAP_ROUTE36) << 8) | MAP_NUM(MAP_ROUTE36), 1, 1, {24}, {9}},
    {(MAP_GROUP(MAP_ROUTE5_POUNAMU) << 8) | MAP_NUM(MAP_ROUTE5_POUNAMU), 0, 2, {24, 23}, {10, 10}},
    {(MAP_GROUP(MAP_ROUTE5_RANGES) << 8) | MAP_NUM(MAP_ROUTE5_RANGES), 1, 1, {23}, {11}},
    {(MAP_GROUP(MAP_ROUTE1_DESERT) << 8) | MAP_NUM(MAP_ROUTE1_DESERT), 0, 3, {22, 22, 21}, {10, 11, 11}},
    {(MAP_GROUP(MAP_ROUTE43_POUNAMU) << 8) | MAP_NUM(MAP_ROUTE43_POUNAMU), 0, 6, {21, 21, 22, 22, 21, 20}, {11, 10, 10, 9, 9, 9}},
    {(MAP_GROUP(MAP_ROUTE3_POUNAMU) << 8) | MAP_NUM(MAP_ROUTE3_POUNAMU), 0, 4, {19, 19, 19, 20}, {8, 9, 10, 10}},
    {(MAP_GROUP(MAP_ROUTE1_KAPITI) << 8) | MAP_NUM(MAP_ROUTE1_KAPITI), 0, 3, {20, 19, 18}, {12, 12, 12}},
    {(MAP_GROUP(MAP_ROUTE6_POUNAMU) << 8) | MAP_NUM(MAP_ROUTE6_POUNAMU), 0, 2, {16, 16}, {11, 10}},
    {(MAP_GROUP(MAP_ROUTE7_POUNAMU) << 8) | MAP_NUM(MAP_ROUTE7_POUNAMU), 0, 7, {15, 14, 13, 13, 13, 12, 12}, {10, 10, 10, 11, 12, 12, 13}},
    {(MAP_GROUP(MAP_ROUTE1_SOUTH) << 8) | MAP_NUM(MAP_ROUTE1_SOUTH), 0, 8, {10, 10, 9, 9, 8, 7, 6, 6}, {13, 12, 12, 13, 13, 13, 13, 14}},
    {(MAP_GROUP(MAP_TE_MATA_TRACK) << 8) | MAP_NUM(MAP_TE_MATA_TRACK), 0, 1, {22}, {13}},
    {(MAP_GROUP(MAP_TE_MATA_SUMMIT) << 8) | MAP_NUM(MAP_TE_MATA_SUMMIT), 0, 1, {22}, {13}},
    {(MAP_GROUP(MAP_RUAPEHU_ASCENT) << 8) | MAP_NUM(MAP_RUAPEHU_ASCENT), 0, 1, {21}, {10}},
    {(MAP_GROUP(MAP_RUAPEHU_SUMMIT) << 8) | MAP_NUM(MAP_RUAPEHU_SUMMIT), 0, 1, {21}, {10}},
    {(MAP_GROUP(MAP_PIOPIOTAHI) << 8) | MAP_NUM(MAP_PIOPIOTAHI), 0, 1, {4}, {9}},
    {(MAP_GROUP(MAP_TAUPO_LAKE_ISLE) << 8) | MAP_NUM(MAP_TAUPO_LAKE_ISLE), 0, 1, {22}, {10}},
};
