Waitohi_MapScripts::
	.byte 0
Waitohi_EventScript_Ferryman::
	msgbox Waitohi_Text_Ferryman, MSGBOX_NPC
	end
Waitohi_EventScript_Woman::
	msgbox Waitohi_Text_Woman, MSGBOX_NPC
	end
Waitohi_EventScript_Kid::
	msgbox Waitohi_Text_Kid, MSGBOX_NPC
	end
Waitohi_EventScript_Sign::
	msgbox Waitohi_Text_Sign, MSGBOX_SIGN
	end
Waitohi_Text_Ferryman:
	.string "Welcome to the Mainland, they'll\ntell you to say. Cheeky, the South.\pFerry's behind me if you ever want\nthe North Island again.\p…Word is the crossing only opened\nfor you. Somebody up top pulled\la string. Wonder who.$"
Waitohi_Text_Woman:
	.string "Off the boat and straight into\nthe sounds. Green water, green\lhills. Breathe it in, love.$"
Waitohi_Text_Kid:
	.string "The dolphins escorted our ferry\nthe whole way in!\pThe South Island shows off. It\nknows it's pretty.$"
Waitohi_Text_Sign:
	.string "WAITOHI\p“Gateway to Te Waipounamu -\nthe waters of greenstone.”$"
