NgamotuGardenerHouse_MapScripts::
	.byte 0

NgamotuGardenerHouse_EventScript_Rhodo::
	lock
	faceplayer
	msgbox NgamotuGardenerHouse_Text_Rhodo, MSGBOX_DEFAULT
	release
	end

NgamotuGardenerHouse_Text_Rhodo:
	.string "The mountain fled here after\n"
	.string "the fight over Pihanga.\l"
	.string "That's the old story.\p"
	.string "He stands apart, sulking in\n"
	.string "his white hood, beautiful and\l"
	.string "alone. You know someone like\l"
	.string "that? Most families have one.$"

