Whakatu_MapScripts::
	.byte 0
Whakatu_EventScript_SunWoman::
	msgbox Whakatu_Text_SunWoman, MSGBOX_NPC
	end
Whakatu_EventScript_GymKid::
	msgbox Whakatu_Text_GymKid, MSGBOX_NPC
	end
Whakatu_EventScript_ArtWoman::
	msgbox Whakatu_Text_ArtWoman, MSGBOX_NPC
	end
Whakatu_EventScript_Kid::
	msgbox Whakatu_Text_Kid, MSGBOX_NPC
	end
Whakatu_EventScript_GymSign::
	msgbox Whakatu_Text_GymSign, MSGBOX_SIGN
	end
Whakatu_Text_SunWoman:
	.string "More sunshine hours than anywhere\nin the country! We keep count.\pIt's a competitive sort of sunny.$"
Whakatu_Text_GymKid:
	.string "Leader Roto runs a FIRE gym in\nthe coldest island. Show-off.\p…He does make good soup, but.$"
Whakatu_Text_ArtWoman:
	.string "Every second person here is a\npotter or a painter.\pThe other half run the cafe that\nsells to the first half.$"
Whakatu_Text_Kid:
	.string "The middle of the whole country's\njust up the hill! There's a sign\land everything!$"
Whakatu_Text_GymSign:
	.string "WHAKATU GYM\nLeader: ROTO - keeps the coals.\p“Warmth is a kind of welcome.”$"
