TamakiCityHouse2_MapScripts::
	.byte 0

TamakiCityHouse2_EventScript_AuntyCity::
	lock
	faceplayer
	msgbox TamakiCityHouse2_Text_AuntyCity, MSGBOX_DEFAULT
	release
	end

TamakiCityHouse2_Text_AuntyCity:
	.string "Three hundred thousand of us\n"
	.string "have whanau in the islands,\l"
	.string "love. City of sails, city of\l"
	.string "cousins.\p"
	.string "Whoever holds that tower, this\n"
	.string "city stays OURS at street\l"
	.string "level. Remember the street\l"
	.string "level.$"

